"""Ouroboros: a bounded, evidence-preserving OOPTDD generation protocol.

The public surface is deliberately namespaced as ``ooptdd.ouroboros`` so generic terms
such as ``step`` and ``Phase`` do not collide with the mature gate API.
"""

from .gate_adapter import (
    GATE_EVIDENCE_VERSION,
    OUROBOROS_GATE_EVIDENCE_SCHEMA,
    GateEvidenceBundle,
    adapt_gate_verification,
    validate_gate_evidence,
)
from .identity import (
    CANONICALIZATION,
    MAX_INTEROPERABLE_INTEGER,
    Digest,
    canonical_json_bytes,
    digest_json,
    digest_raw,
    raw_sha256,
    receipt_content_digest,
)
from .model import (
    PROTOCOL_VERSION,
    RECEIPT_VERSION,
    CycleIdentity,
    CycleSnapshot,
    Disposition,
    EffectClass,
    EffectIntent,
    EffectKind,
    EventKind,
    EventRecord,
    EvidenceTier,
    FindingDisposition,
    InterruptReason,
    MaterialLock,
    MonitorVerdict,
    ObservationVerdict,
    OracleBoundary,
    Phase,
    ProtocolBudget,
    ProtocolEvent,
    RunEvidence,
    RunOutcome,
    RunRole,
    TransitionResult,
)
from .ports import EffectResult, EffectSink, ReceiptStore, SnapshotStore
from .reducer import step
from .schema import (
    LEGACY_RECEIPT_VERSION,
    OUROBOROS_RECEIPT_SCHEMA,
    receipt_from_snapshot,
    successor_from_receipt,
    upcast_v1_receipt,
    validate_receipt,
)

__all__ = [
    "CANONICALIZATION",
    "GATE_EVIDENCE_VERSION",
    "LEGACY_RECEIPT_VERSION",
    "MAX_INTEROPERABLE_INTEGER",
    "OUROBOROS_RECEIPT_SCHEMA",
    "OUROBOROS_GATE_EVIDENCE_SCHEMA",
    "PROTOCOL_VERSION",
    "RECEIPT_VERSION",
    "CycleIdentity",
    "CycleSnapshot",
    "Digest",
    "Disposition",
    "EffectClass",
    "EffectIntent",
    "EffectKind",
    "EffectResult",
    "EffectSink",
    "EventKind",
    "EventRecord",
    "EvidenceTier",
    "FindingDisposition",
    "GateEvidenceBundle",
    "InterruptReason",
    "MaterialLock",
    "MonitorVerdict",
    "ObservationVerdict",
    "OracleBoundary",
    "Phase",
    "ProtocolBudget",
    "ProtocolEvent",
    "ReceiptStore",
    "RunEvidence",
    "RunOutcome",
    "RunRole",
    "SnapshotStore",
    "TransitionResult",
    "adapt_gate_verification",
    "canonical_json_bytes",
    "digest_json",
    "digest_raw",
    "raw_sha256",
    "receipt_content_digest",
    "receipt_from_snapshot",
    "successor_from_receipt",
    "step",
    "upcast_v1_receipt",
    "validate_receipt",
    "validate_gate_evidence",
]
