"""Generate docs/receipts/contract-mock-parity-2026-07-22.md from LIVE runs.

# KG: contract-mock-parity-receipt-2026-07-22

Runs the contract↔mock parity wings for real and writes the receipt document
from the events the verifier actually read back — the committed doc quotes a
positive log, never a hand-written claim. The raw JSONL wing store is committed
alongside the markdown so the log itself is diffable evidence.

    python scripts/gen_parity_receipt.py          # mock + jsonl wing (always)
    OOPTDD_OO_URL=... OOPTDD_OO_PASSWORD=...      # + live OpenObserve wing
"""
from __future__ import annotations

import json
import os
import sys
import time
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

from ooptdd.backends import get_backend  # noqa: E402
from ooptdd.backends.conformance import assert_backend_conforms  # noqa: E402
from ooptdd.backends.jsonl import JsonlBackend  # noqa: E402
from ooptdd.backends.memory import MemoryBackend  # noqa: E402
from ooptdd.engine.gate import evaluate  # noqa: E402
from ooptdd.engine.verify import verify_gate  # noqa: E402
from tests.test_contract_mock_parity_receipt import (  # noqa: E402  the single vocabulary
    CLAUSES,
    KG_ID,
    _receipt_gate,
    _ship_receipt,
)

OUT_DIR = ROOT / "docs" / "receipts"
OUT_MD = OUT_DIR / "contract-mock-parity-2026-07-22.md"
OUT_JSONL = OUT_DIR / "contract-mock-parity-2026-07-22.events.jsonl"


def _fmt_events(events: list[dict]) -> str:
    keys = ("_timestamp", "event", "clause", "result", "subject", "kg")
    lines = [json.dumps({k: e[k] for k in keys if k in e}, ensure_ascii=False)
             for e in sorted(events, key=lambda e: e.get("_timestamp", 0))]
    return "\n".join(lines)


def run_mock_wing() -> tuple[str, str, dict]:
    assert_backend_conforms(lambda: MemoryBackend(), cid=f"parity-mem-{uuid.uuid4().hex[:8]}")
    cid = f"parity-receipt-{uuid.uuid4().hex[:8]}"
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if OUT_JSONL.exists():
        OUT_JSONL.unlink()  # fresh store per generation: `== 1` clause counts stay honest
    _ship_receipt(JsonlBackend(path=str(OUT_JSONL)), cid, subject="MemoryBackend")
    reader = JsonlBackend(path=str(OUT_JSONL))  # a fresh handle re-reads from disk
    res = evaluate(reader, _receipt_gate(cid, "MemoryBackend"))
    assert res["ok"], f"mock-wing receipt gate RED: {res}"
    log = _fmt_events(reader.query(cid, since_us=int((time.time() - 3600) * 1_000_000), until_us=int((time.time() + 3600) * 1_000_000)).events)
    return cid, log, res


def run_oo_wing() -> tuple[str, str, dict] | None:
    if not (os.getenv("OOPTDD_OO_URL") and os.getenv("OOPTDD_OO_PASSWORD")):
        return None
    make = lambda: get_backend("openobserve", stream="conformance")  # noqa: E731
    last = None
    for _ in range(3):
        try:
            assert_backend_conforms(make, cid=f"parity-oo-{uuid.uuid4().hex[:8]}")
            last = None
            break
        except AssertionError as exc:
            last = exc
            time.sleep(2.0)
    if last is not None:
        raise last
    cid = f"parity-oo-receipt-{uuid.uuid4().hex[:8]}"
    _ship_receipt(make(), cid, subject="OpenObserveBackend")
    res = verify_gate(make(), cid, _receipt_gate(cid, "OpenObserveBackend"),
                      retries=6, delay=1.0)
    assert res["verdict"] == "present", f"live receipt did not arrive: {res}"
    log = _fmt_events(make().query(cid, since_us=int((time.time() - 3600) * 1_000_000), until_us=int((time.time() + 3600) * 1_000_000)).events)
    return cid, log, res


def main() -> int:
    mock_cid, mock_log, mock_res = run_mock_wing()
    oo = run_oo_wing()
    checks_n = len(mock_res["checks"])

    doc = f"""# Receipt: contract↔mock parity — positive log

`# KG: {KG_ID}`

**Claim.** `MemoryBackend` (the mock) is a legitimate stand-in for a real store
because (a) it passes the **identical executable contract** every real driver
must pass — the same `assert_backend_conforms` callable in
`src/ooptdd/backends/conformance.py`, covering {len(CLAUSES)} clauses
({", ".join(CLAUSES)}) — and (b) it **never overclaims**: its typed caps refuse
the external-judge role (`independent=False`) that the real stores carry.
This is OOPTDD-R05 ("mock as contract candidate") made executable.

**Why this document is trustworthy.** It is generated by
`scripts/gen_parity_receipt.py` from events a verifier **read back from a
store** — not from the test's return value. The permanent, re-verified form is
`tests/test_contract_mock_parity_receipt.py` (CI-resident; a receipt that only
runs in its author's session is not adoption). Regenerate any time:
`python scripts/gen_parity_receipt.py`.

## Wing 1 — mock wing (always on)

The mock passed all {len(CLAUSES)} contract clauses; the receipt was shipped to a
**cross-process JSONL store** (a different store class than the subject under
audit, re-read from disk by a fresh handle) and the arrival gate evaluated
{checks_n} checks GREEN (per-clause `== 1` value-pinned counts + the
`result=violated` negative wing + the verdict event).

cid: `{mock_cid}` — the raw store file is committed as
[`contract-mock-parity-2026-07-22.events.jsonl`](contract-mock-parity-2026-07-22.events.jsonl);
the verifier's readback:

```json
{mock_log}
```
"""
    if oo:
        oo_cid, oo_log, oo_res = oo
        doc += f"""
## Wing 2 — live OpenObserve wing (the real store, same contract function)

`OpenObserveBackend` passed the **same** `assert_backend_conforms` callable
against a live OpenObserve; the receipt was arrival-polled to the full
configured window (`verify_gate` → verdict `{oo_res["verdict"]}`; this gate's
`==`-count and `absent` checks are anti-monotone, so early settle is forbidden
and the reported attempts ({oo_res.get("attempts")}) always equals the
configured retries — it is the poll count, NOT an arrival-latency signal).
The mock and the real store were judged by one contract — parity is a fact of
execution, not of documentation.

Note: this live wing is env-gated and **skips in hosted CI** (no store secrets
there) — the readback below is a locally generated artifact, re-runnable via
this script; the CI-resident, always-on form is the mock/JSONL wing.

cid: `{oo_cid}` — the verifier's readback from OpenObserve:

```json
{oo_log}
```
"""
    else:
        doc += """
## Wing 2 — live OpenObserve wing

Not run in this generation (OOPTDD_OO_URL/OOPTDD_OO_PASSWORD unset). The
env-gated test `test_real_openobserve_satisfies_the_identical_contract_with_arrival_receipt`
runs the same wing whenever the store is available.
"""
    doc += """
## The split that keeps it honest

| | contract (`assert_backend_conforms`) | external judge (`caps.independent`) |
|---|---|---|
| `MemoryBackend` (mock) | ✅ same callable | ❌ refused — proves *mechanics* |
| `OpenObserveBackend` | ✅ same callable | ✅ carried — proves *arrival* |

A mock that passed a *different* contract would be drift waiting to happen; a
mock that claimed *independence* would be a false judge. This receipt pins both
halves, with Longinus anchors (`# KG: contract-mock-parity-receipt-2026-07-22`)
in `backends/conformance.py`, `backends/memory.py`, the test, this script, and
this document.
"""
    OUT_MD.write_text(doc)
    print(f"wrote {OUT_MD}")
    print(f"wrote {OUT_JSONL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
