#!/usr/bin/env python3
"""One-shot reconcile of all ooptdd consumers to canonical — divergence-aware.

WHY this exists (measured 2026-06-16): the three consumers were vendored with
*different* conventions, so the plain ``vendor_ooptdd.py <consumer>`` cannot
uniformly re-vendor them, and two of them silently lag canonical:

    consumer     vendored dir         manifest                       drift test loc   canonical-compare guard
    prismv2      tests/_vendor/ooptdd ooptdd_manifest.json           tests/           YES  (catches lag -> RED now)
    jg_bpc       _vendor/ooptdd       ooptdd_vendor_manifest.json    _vendor/         NO   (in sync, so green)
    lakatotree   _vendor/ooptdd       ooptdd_vendor_manifest.json    _vendor/         NO   (BEHIND but green = silent stale)

Measured lag vs *committed* canonical (HEAD), independent of any uncommitted WIP:
    prismv2, lakatotree  : behind on verify.py + backends/{base,memory,openobserve,otel}.py
                           (= the committed SOLID-P2 "no silent green" fix, not yet vendored)
    jg_bpc               : in sync

This tool standardizes ALL consumers on: normalized-sha256 manifest + the strong
2-guard drift test (manifest integrity + canonical-compare), each written at that
consumer's existing file locations (no file moves -> no orphans).

SAFETY: ``--apply`` REFUSES while canonical ``src/ooptdd`` has uncommitted changes,
so it can never vendor a moving WIP target (e.g. the in-flight OpenSLO gate.py).
Run ``--check`` (default) any time: it reports the pending per-file delta and the
dirty-guard state, and writes nothing.

    python scripts/reconcile_consumers.py            # dry-run, no writes
    python scripts/reconcile_consumers.py --apply    # only once canonical is clean
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
OOPTDD = _HERE.parent
SRC = OOPTDD / "src" / "ooptdd"

# Consumer checkouts resolve under OOPTDD_CONSUMERS_ROOT (default: the workspace that holds this
# repo) + the consumer's dir, so the registry is not pinned to one machine's absolute paths — the
# old hardcoded /mnt/hdd/... roots were dead on every other box and silently SKIPped every consumer
# (a reconcile that finds nothing reads as "all in sync").
_CONSUMERS_ROOT = Path(os.getenv("OOPTDD_CONSUMERS_ROOT", str(OOPTDD.parent)))

VENDOR_FILES = [
    "__init__.py", "model.py", "verify.py", "config.py", "plugin.py", "cli.py",
    "gate.py", "ontology.py", "assertions.py", "semconv.py",
    "backends/__init__.py", "backends/base.py", "backends/memory.py",
    "backends/openobserve.py", "backends/otel.py", "backends/clickhouse.py",
]

# (root, vendor_dir rel-to-root, manifest rel-to-root, test rel-to-root,
#  vendor rel-to-TESTFILE, manifest rel-to-TESTFILE)
CONSUMERS = [
    {"name": "prismv2",
     "dir": "prismv2",
     "vendor": "tests/_vendor/ooptdd",
     "manifest": "tests/_vendor/ooptdd_manifest.json",
     "test": "tests/test_ooptdd_vendor_drift.py",
     "vendor_rel": "_vendor/ooptdd",
     "manifest_rel": "_vendor/ooptdd_manifest.json"},
    {"name": "jg_bpc",
     "dir": "3d_vision_jg_bpc",
     "vendor": "_vendor/ooptdd",
     "manifest": "_vendor/ooptdd_vendor_manifest.json",
     "test": "_vendor/test_ooptdd_vendor_drift.py",
     "vendor_rel": "ooptdd",
     "manifest_rel": "ooptdd_vendor_manifest.json"},
    {"name": "lakatotree",
     "dir": "lakatotree",
     "vendor": "_vendor/ooptdd",
     "manifest": "_vendor/ooptdd_vendor_manifest.json",
     "test": "_vendor/test_ooptdd_vendor_drift.py",
     "vendor_rel": "ooptdd",
     "manifest_rel": "ooptdd_vendor_manifest.json"},
]


def nsha(text: str) -> str:
    """Normalized sha256 — strip trailing ws/CRLF/trailing-newline so a cosmetic
    reformat doesn't false-RED. Same rule as vendor_ooptdd.py."""
    lines = [ln.rstrip() for ln in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    return hashlib.sha256(("\n".join(lines).rstrip("\n") + "\n").encode()).hexdigest()


def canonical_dirty() -> list[str]:
    r = subprocess.run(["git", "status", "--short", "src/ooptdd"],
                       cwd=OOPTDD, capture_output=True, text=True, check=True)
    return [ln for ln in r.stdout.splitlines() if ln.strip()]


def canonical_hashes() -> dict[str, str]:
    return {rel: nsha((SRC / rel).read_text()) for rel in VENDOR_FILES}


# Strong drift test, parameterized per-consumer. Normalized hashing so it agrees
# with the manifest this tool writes. Two guards: manifest integrity (runs anywhere)
# + canonical-compare (runs on a dev box where the canonical checkout is present).
_TEST_TEMPLATE = '''\
"""Vendored ooptdd integrity — generated by ooptdd/scripts/reconcile_consumers.py.

Distribution model = vendored core + drift-check. Two guards keep the copy honest:
1. test_vendored_files_match_manifest  — every vendored file matches its pinned
   normalized-sha256 (catches a local edit/tamper; needs no canonical repo).
2. test_vendored_matches_canonical_when_present — when the canonical checkout
   exists (dev box / OOPTDD_CANONICAL), the vendored copy must equal it; else
   re-vendor. THIS is the guard that catches "canonical moved on, we lagged".

Re-vendor: python <ooptdd>/scripts/reconcile_consumers.py --apply
"""
import hashlib
import json
import os
from pathlib import Path

import pytest

_HERE = Path(__file__).resolve().parent
_VENDOR = _HERE / "{vendor_rel}"
_MANIFEST = _HERE / "{manifest_rel}"


def _nsha(text: str) -> str:
    lines = [ln.rstrip() for ln in text.replace("\\r\\n", "\\n").replace("\\r", "\\n").split("\\n")]
    return hashlib.sha256(("\\n".join(lines).rstrip("\\n") + "\\n").encode()).hexdigest()


def _manifest() -> dict:
    return json.loads(_MANIFEST.read_text())


def test_vendored_files_match_manifest():
    files = _manifest()["files"]
    for rel, sha in files.items():
        f = _VENDOR / rel
        assert f.exists(), f"vendored ooptdd/{{rel}} missing"
        assert _nsha(f.read_text()) == sha, f"vendored ooptdd/{{rel}} drifted from manifest — re-vendor"
    present = {{str(p.relative_to(_VENDOR)).replace(os.sep, "/") for p in _VENDOR.rglob("*.py")}}
    assert present == set(files), f"vendor tree != manifest (symmetric diff): {{present ^ set(files)}}"


def test_vendored_matches_canonical_when_present():
    root = os.getenv("OOPTDD_CANONICAL")
    canon = Path(root) / "src" / "ooptdd" if root else None
    if canon is None or not canon.exists():
        pytest.skip("OOPTDD_CANONICAL unset or absent — offline; manifest guard covers integrity")
    for rel in _manifest()["files"]:
        c = canon / rel
        assert c.exists(), f"canonical dropped ooptdd/{{rel}} — re-vendor"
        assert _nsha(c.read_text()) == _nsha((_VENDOR / rel).read_text()), \\
            f"vendored ooptdd/{{rel}} behind canonical — re-vendor"
'''


def reconcile_one(c: dict, canon_h: dict, apply: bool) -> dict:
    root: Path = _CONSUMERS_ROOT / c["dir"]
    vdir = root / c["vendor"]
    mpath = root / c["manifest"]
    tpath = root / c["test"]
    report = {"name": c["name"], "lag": [], "ok": root.is_dir()}
    if not report["ok"]:
        return report
    # measure current lag vs canonical
    for rel in VENDOR_FILES:
        vf = vdir / rel
        cur = nsha(vf.read_text()) if vf.exists() else None
        if cur != canon_h[rel]:
            report["lag"].append(rel if cur is not None else rel + "(missing)")
    if not apply:
        return report
    # write: copy files, manifest, strong test
    manifest = {"ooptdd_version": _version(), "files": {}}
    (vdir / "backends").mkdir(parents=True, exist_ok=True)
    for rel in VENDOR_FILES:
        text = (SRC / rel).read_text()
        (vdir / rel).write_text(text)
        manifest["files"][rel] = nsha(text)
    mpath.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    tpath.write_text(_TEST_TEMPLATE.format(vendor_rel=c["vendor_rel"],
                                           manifest_rel=c["manifest_rel"]))
    report["written"] = True
    return report


def _version() -> str:
    for ln in (SRC / "__init__.py").read_text().splitlines():
        if ln.startswith("__version__"):
            return ln.split("=", 1)[1].strip().strip('"').strip("'")
    return "0"


def main(argv=None) -> int:
    args = sys.argv[1:] if argv is None else argv
    apply = "--apply" in args
    dirty = canonical_dirty()
    print(f"canonical src/ooptdd dirty: {bool(dirty)}"
          + (f"  -> {[d.split()[-1] for d in dirty]}" if dirty else ""))
    if apply and dirty:
        print("\nREFUSING --apply: canonical has uncommitted changes. Re-vendoring now "
              "would bake a moving WIP target. Commit canonical first, then re-run.",
              file=sys.stderr)
        return 1
    canon_h = canonical_hashes()
    print(f"mode: {'APPLY' if apply else 'CHECK (dry-run, no writes)'}\n")
    any_lag = False
    for c in CONSUMERS:
        r = reconcile_one(c, canon_h, apply)
        if not r["ok"]:
            print(f"  {r['name']:<11} : SKIP (root not found)")
            continue
        status = "in sync" if not r["lag"] else f"BEHIND on {r['lag']}"
        any_lag = any_lag or bool(r["lag"])
        suffix = "  -> re-vendored + strong test written" if r.get("written") else ""
        print(f"  {r['name']:<11} : {status}{suffix}")
    if not apply:
        print(f"\n{'lag present — run --apply once canonical is clean' if any_lag else 'all in sync'}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
